---
interfaces:
  Ethernet 112:
     - ip: 192.168.1.3/31
  Ethernet 40: 
     - ip: 192.168.1.7/31
  Ethernet 4: 
     - ip: 110.1.1.2/24
  Loopback 0:
     - ip: 100.1.1.3/32
  Ethernet 0:
     - channel_grp: 1
  
mclag:
  source_ip: 110.1.1.2
  peer_ip: 110.1.1.1

bgp:
  asn: 65011
  remote_asn: 
    - 65012
  neighbor_1_ip: 192.168.1.2
  neighbor_2_ibgp_ip: 192.168.1.6 
  neighbor_1_source_ip: 100.1.1.1  
