---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - dellemc_networking.sonic
  tasks:
    - name: "Test delete_api"
      sonic_api:
        url: data/openconfig-interfaces:interfaces/interface=Ethernet64/subinterfaces/subinterface=0/openconfig-if-ip:ipv4/addresses/address=1.1.1.1/config/prefix-length
        method: "DELETE"
        status_code: 204
