---
- hosts: datacenter
  connection: network_cli
  gather_facts: no
  collections:
     - dellemc.sonic
  tasks:
  - name: "Configure username and password for SONiC device along with 'save'"
    sonic_config:
      commands: ['snmp-server community public group ro']
      save: yes

  - name: "Configure interface description using 'parents' option on SONiC device"
    sonic_config:
      lines:
        - description "hi"
      parents: ['interface Ethernet 60']
 
  - name: "Configure bgp using multiple level 'parents' on SONiC device"
    sonic_config:
      lines:
        - maximum-paths 4
      parents: ['router bgp 4', 'address-family ipv4 unicast']

  - name: "Configure ip access-list using 'before' and 'after' option on SONiC device"
    sonic_config:
      lines:
        - seq 1 permit tcp any any ack
      parents: ['ip access-list test']
      before: ['no ip access-list test']
      after: ['no ip access-list test']

  # Export the following variable in the environment for using source, ANSIBLE_NETWORK_GROUP_MODULES=sonic 
  - name: "Configure cli using source file"
    sonic_config:
      src: ../tests/regression/sonic_config/src.txt
 
  - name: "Configure cli with prompts on SONiC device"
    sonic_config:
      commands:
        - command: 'do image remove all'
          prompt: '\[y/N\]:$'
          answer: 'N'
