---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
    - dellemc.sonic
  tasks:
    - name: "Test sonic_interfaces"
      sonic_interfaces:
        config:
          - name: Ethernet64
            description: "hi test"
            enabled: False
          - name: Ethernet40
            description: "hi ans"
            enabled: False
        state: merged
