---
interfaces:
  Ethernet 112:
      - ip: 192.168.1.5/31
  Ethernet 40:
      - ip: 192.168.1.9/31
  Ethernet 4:
      - ip: 110.1.1.4/24
  Loopback 0:
      - ip: 100.1.1.5/32
  Ethernet 0:
      - channel_grp: 1

mclag:
  source_ip: 110.1.1.4
  peer_ip: 110.1.1.3

bgp:
  asn: 65013
  remote_asn: 
    - 65012
  neighbor_1_ip: 192.168.1.12
  neighbor_2_ibgp_ip: 192.168.1.8
  neighbor_1_source_ip: 100.1.1.1
