---
- name: Ansible resource module example
  hosts: datacenter
  gather_facts: False
  connection: httpapi
  collections:
     - dellemc_networking.sonic
  tasks:
    - name: "Test get_api"
      sonic_api:
        url: data/openconfig-interfaces:interfaces/interface=Ethernet64
        method: "GET"
        status_code: 200
